### PR TITLE
Bugfix/emp3 web#22 ww map swap

### LINKED ISSUE #22: Worldwind map fails to load when performing a map swap
When performing a map swap, swapping to worldwind fails to load the worldwind base map layer. Only a gray screen appears. A green toastr message appears in the upper right of the browser indicating a successful swap operation. The failure occurs in emp-2834 and development branches. Cesium and Leaflet have no issues performing map swap.

### PR DESCRIPTION
**Pull request by jaybarra**
resolves #22 
There needed to be a delay added to the startup for the map to swap successfully.

### CODE REVIEW

File: src/mapengine/worldwind/manifest.js [hunk 1]
```diff
@@ -49,8 +49,8 @@ function initializeWorldwind(args) {
       }
 
       var empWorldWind = new EMPWorldWind.map(wwd);
-      empWorldWind.initialize(instArgs.mapInstance);
-      empWorldWind.isV2Core = false;
+      // This delay is necessary for swapping maps, the underlying reason is not understood yet however
+      setTimeout(empWorldWind.initialize, 150, instArgs.mapInstance);
```
Comment (jaybarra) [inline src/mapengine/worldwind/manifest.js]: This fixed the gray screen issue
